drone:
  max_speed: 5.0 # m/s
  pid_gains:
    kp: 1.0
    ki: 0.1
    kd: 0.05

mqtt:
  broker: "localhost"
  port: 1883
  topic: "drone/telemetry"

ble:
  scan_interval: 5 # seconds

ble_beacons:
  - uuid: "12345678-1234-1234-1234-1234567890ab"

beacons:
  "2dc76ea3-6668-48da-9866-75be8bc86f4d": # Beacon 1 UUID
    location: "one"
  "8ec76ea3-6668-48da-9866-75be8bc86f4d": # Beacon 2 UUID
    location: "two"
  "6cc76ea3-6668-48da-9866-75be8bc86f4d": # Beacon 3 UUID
    location: "three"
